name: Tests

on: [push, pull_request]

concurrency:
    group: ${{ github.ref_name }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        name: "Static analysis"
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2

            - name: Install dependencies
              run: composer install --no-interaction

            - name: Lint code
              run: ./vendor/bin/phpcs --standard=PSR12 ./src ./tests

    test:
        concurrency: ${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.stability }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest, windows-latest]
                php:
                    - version: 7.2
                      phpunit: 8
                    - version: 7.3
                      phpunit: 8
                    - version: 7.4,
                      phpunit: 8
                    - version: 8.0
                      phpunit: 8
                    - version: 8.1,
                      phpunit: 8
                    - version: 8.2
                      phpunit: 8
                stability: [prefer-stable]

        name: P${{ matrix.php.version }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php.version }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            - name: Install dependencies
              run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction && composer global require phpunit/phpunit "^${{ matrix.php.phpunit }}"

            - name: Execute tests
              run: phpunit --version && phpunit
